name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore

    - name: Read infra tests
      run: dotnet test RecklessSpeech.Infrastructure.Read.Tests\RecklessSpeech.Infrastructure.Read.Tests.csproj --no-build --verbosity normal

    - name: Write infra tests
      run: dotnet test RecklessSpeech.Infrastructure.Sequences.Tests\RecklessSpeech.Infrastructure.Sequences.Tests.csproj --no-build --verbosity normal      
    
    - name: Acceptance tests
      run: dotnet test RecklessSpeech.AcceptanceTests\RecklessSpeech.AcceptanceTests.csproj --no-build --verbosity normal

    - name: Write sequences tests
      run: dotnet test RecklessSpeech.Application.Write.Sequences.Tests\RecklessSpeech.Application.Write.Sequences.Tests.csproj --no-build --verbosity normal

